develpment:
  sessions:
    default:
      database: remind_me_to_live_development
      hosts:
        - localhost:27017

test: &TEST
  sessions:
    default:
      database: remind_me_to_live_test
      hosts:
        - localhost:27017

cucumber:
    <<: *TEST

