development:
  sessions:
    default:
      database: remind_me_to_live_test
      hosts:
        - localhost:27017
test: &TEST
  sessions:
    default:
      database: remind_me_to_live_test
      hosts:
        - localhost:27017
  #options:
  #  identity_map_enabled: true

production:
  sessions:
    default:
      database: remind_me_to_live_test
      hosts:
        - mongodb://remindmetolive:Qwerty123@ds037987-a.mongolab.com:37987/heroku_app7871152

cucumber:
    <<: *TEST

